import type { ProjectSummaryNarrative } from "./ProjectSummaryNarrative";

export const projectSummaries: ProjectSummaryNarrative[] = [
  {
    publishedUrl: "https://snerks.github.io/tab-player-app/",
    imageUrl: "/images/tab-player-app.png",
    title: "React Guitar Tab Player App",
    description: "A Guitar Tab player",
    technologies: ["React", "Material UI", "TypeScript", "Tone"],
  },
  {
    publishedUrl: "https://snerks.github.io/mui-recommended-gigs-01/",
    imageUrl: "/images/snerks.github.io_mui-recommended-gigs-01.png",
    title: "React Event Management System",
    description: "An entertainment event management system.",
    technologies: [
      "React Hooks",
      "React Router",
      "Firebase",
      "Formik 2",
      "Yup",
      "Material UI",
      "TypeScript",
    ],
  },

  {
    publishedUrl: "https://snerks.github.io/hr-workflow-app/",
    imageUrl: "/images/hr-workflow-app.300.png",
    title: "React Workflow System",
    description: "A configurable workflow system.",
    technologies: [
      "React",
      "Vite",
      "React Router",
      "TypeScript",
      "Material UI",
    ],
  },
  {
    publishedUrl: "https://snerks.github.io/reversi-ts-app/",
    imageUrl: "/images/reversi-app-2025.300.png",
    title: "React Reversi",
    description: "A board game, with computer player.",
    technologies: ["React 19", "TypeScript", "Vite"],
  },
  {
    publishedUrl: "https://snerks.github.io/snooker-scorer-app/",
    imageUrl: "/images/snooker-scorer-app.cropped.png",
    title: "React Snooker Scoring App",
    description: "Allows scoring for a snooker frame, in real time.",
    technologies: ["React 19", "TypeScript", "Vite"],
  },
  {
    publishedUrl: "https://snerks.github.io/fsa-ratings-ng/",
    imageUrl: "/images/fsa-ratings-ng.300.png",
    title: "Angular Food Business Rating System",
    description:
      "A client app allowing search for the FSA Ratings for food businesses in the UK.",
    technologies: [
      "Angular 12",
      "Angular Material",
      "REST API",
      "Material UI",
      "TypeScript",
    ],
  },
  {
    publishedUrl: "https://snerks.github.io/fix-protocol-app/",
    imageUrl: "/images/fixprotocol.decoder.app.300.png",
    title: "React FIX Protocol Message Decoder",
    description:
      "A client app allowing FIX Messages to be decoded to a human-readable form.",
    technologies: ["React 19", "Vite", "Material UI", "TypeScript"],
  },
  {
    publishedUrl: "https://snerks.github.io/Copilot-Todo/",
    imageUrl: "/images/todo-app.300.png",
    title: "React Todo App",
    description: "A client app allowing users to manage daily tasks.",
    technologies: ["React 19", "Vite", "Material UI", "TypeScript"],
  },
  {
    publishedUrl: "https://snerks.github.io/reactive-forms01/",
    imageUrl: "/images/snerks.github.io_reactive-forms01_create.png",
    title: "Angular Event Management System",
    description: "An entertainment event management system.",
    technologies: [
      "Angular",
      "Reactive Forms",
      "Firebase",
      "Bootstrap",
      "TypeScript",
    ],
  },
  {
    publishedUrl: "https://snerks.github.io/store-admin-panel/dashboard/",
    imageUrl: "/images/ng-dashboard.300.png",
    title: "Angular Dashboard System",
    description: "A sample dashboard system, with Material UI and ChartJS.",
    technologies: ["Angular", "Material UI", "ChartJS", "TypeScript"],
  },
  {
    publishedUrl: "https://snerks.github.io/footballstats-ts-app/",
    imageUrl: "/images/football-stats-01.300.png",
    title: "React Chart App",
    description: "A responsive charting app, powered by ChartJs.",
    technologies: ["React", "ChartJs", "TypeScript"],
  },
  {
    publishedUrl: "https://snerks.github.io/exchange-rate-app/",
    imageUrl: "/images/react-ts-exchange-rates.300.png",
    title: "React Exchange Rate App",
    description: "An app to view Exchange Rates",
    technologies: ["REST API", "Material UI", "TypeScript"],
  },
  {
    publishedUrl: "https://snerks.github.io/BlazorApp322/",
    imageUrl: "/images/blazor-app-01.300.png",
    title: "Blazor WASM REST App",
    description: "A sample app, powered by Blazor WASM.",
    technologies: ["Blazor WASM", "REST API", "Bootstrap", "C#"],
  },
  {
    publishedUrl: "https://snerks.github.io/react-bootstrap-ts-website/",
    imageUrl: "/images/react-bootstrap-site-01.300.png",
    title: "React Bootstrap Website",
    description: "A marketing web site, using React and Bootstrap.",
    technologies: ["React", "Bootstrap", "TypeScript"],
  },
  {
    publishedUrl: "https://snerks.github.io/my-blog-starter/",
    imageUrl: "/images/gatsby-starter-blog.300.png",
    title: "Gatsby Blog",
    description: "A blog site, powered by Gatsby.",
    technologies: ["Gatsby", "React", "Graphql"],
  },
  {
    publishedUrl: "https://snerks.github.io/asteroids-react-ts-01/",
    imageUrl: "/images/space-game.01.300.png",
    title: "Space Game",
    description: "A space game, implemented with React.",
    technologies: ["React", "TypeScript"],
  },
];
